import type { Page } from '@playwright/test';
import { test, expect } from '../../fixtures';
import { TRACKS, SCROBBLE_MIN_SECONDS } from '../../fixtures/constants';
import { isRealScrobble, isJellyfinPlaybackStopped } from '../../fixtures/scrobbleHelpers';

// Playwright determines which fixtures a test needs by statically parsing the
// literal destructuring pattern in each test() callback — it cannot resolve a
// computed property name (e.g. `{ [fixture]: { window } }`) at runtime, so the
// four backend combinations below are intentionally written out as literal
// test.describe blocks rather than generated by looping over an array. Shared
// logic lives in these helper functions so the test bodies aren't duplicated.

async function runScrobbleSentAfterThreshold(window: Page, isScrobble: (url: string) => boolean) {
  const scrobblePromise = window.waitForRequest((req) => isScrobble(req.url()), {
    timeout: (SCROBBLE_MIN_SECONDS + 30) * 1000,
  });

  await window.click('[data-testid="nav-albums"]');
  await expect(window.locator(`text=${TRACKS.track01.album}`).first()).toBeVisible({
    timeout: 15_000,
  });
  // Albums require a double-click to navigate in — a single click only selects
  // the row (see AlbumList.tsx's useListClickHandler: doubleClick navigates,
  // there is no singleClick override).
  await window.locator(`text=${TRACKS.track01.album}`).first().dblclick();
  await window.locator(`text=${TRACKS.track01.title}`).first().dblclick();
  await window.waitForSelector('[data-testid="player-bar"]');

  const req = await scrobblePromise;
  expect(isScrobble(req.url())).toBe(true);
}

async function runScrobbleNotSentBeforeThreshold(
  window: Page,
  isScrobble: (url: string) => boolean
) {
  let scrobbleCalled = false;
  await window.route('**/*', async (route) => {
    if (isScrobble(route.request().url())) scrobbleCalled = true;
    await route.continue();
  });

  await window.click('[data-testid="nav-albums"]');
  await expect(window.locator(`text=${TRACKS.track01.album}`).first()).toBeVisible({
    timeout: 15_000,
  });
  // Albums require a double-click to navigate in — a single click only selects
  // the row (see AlbumList.tsx's useListClickHandler: doubleClick navigates,
  // there is no singleClick override).
  await window.locator(`text=${TRACKS.track01.album}`).first().dblclick();
  await window.locator(`text=${TRACKS.track01.title}`).first().dblclick();
  await window.waitForTimeout(5000); // 5s — well below 30s minimum

  await window.click('[data-testid="player-next"]');
  await window.waitForTimeout(2000);
  expect(scrobbleCalled).toBe(false);
}

async function runSeekBackwardNoDoubleScrobble(window: Page, isScrobble: (url: string) => boolean) {
  test.setTimeout(240_000);

  // Use the solo track — it's the only track in its album, so once it reaches its
  // natural end the queue just stops. The scrobble threshold (90% of 62s = 55.8s)
  // leaves only ~6.2s of margin before this track naturally ends, regardless of
  // where within it we seek back to — using a multi-track album here would risk
  // rolling into a second track whose own legitimate scrobble would pollute the count
  // no matter how the wait times are tuned.
  await window.click('[data-testid="nav-albums"]');
  await expect(window.locator(`text=${TRACKS.soloTrack.album}`).first()).toBeVisible({
    timeout: 15_000,
  });
  // Albums require a double-click to navigate in — a single click only selects
  // the row (see AlbumList.tsx's useListClickHandler: doubleClick navigates,
  // there is no singleClick override).
  await window.locator(`text=${TRACKS.soloTrack.album}`).first().dblclick();
  await window.locator(`text=${TRACKS.soloTrack.title}`).first().dblclick();
  await window.waitForSelector('[data-testid="player-bar"]');

  // React to the actual scrobble instead of a fixed wait — resolves as soon as the
  // request is observed, so there's no risk of overshooting past the track's end.
  await window.waitForRequest((req) => isScrobble(req.url()), {
    timeout: (SCROBBLE_MIN_SECONDS + 30) * 1000,
  });

  // First scrobble just fired — immediately seek to the MIDDLE of the track via
  // mouse click at 50% of the seek bar width. Track still has ~6 seconds left
  // before its natural end at this point, so we act right away. NOT seeking to
  // the beginning — that resets the hasScrobbled flag and WOULD legitimately
  // trigger a second scrobble once the threshold is re-crossed; that behavior is
  // intentionally not what this test checks.
  const seekBar = window.locator('[data-testid="player-seek-bar"]');
  const box = await seekBar.boundingBox();
  if (!box) throw new Error('player-seek-bar not found or not visible');
  await window.mouse.click(box.x + box.width * 0.5, box.y + box.height / 2);

  // Now count any further scrobbles — there should be none.
  let secondScrobbleCount = 0;
  await window.route('**/*', async (route) => {
    if (isScrobble(route.request().url())) secondScrobbleCount++;
    await route.continue();
  });

  // Wait for the track to play to the end from the middle (~31s) plus buffer —
  // comfortably covers both re-crossing the threshold (~25s) and the track's own
  // natural end. Since this is a single-track album, reaching the end just stops
  // playback, with nothing further to scrobble.
  await window.waitForTimeout(40_000);
  expect(secondScrobbleCount).toBe(0);
}

test.describe('Scrobbling — Navidrome + Web Audio', () => {
  test('scrobble sent after playing past threshold', async ({ navidromeApp: { window } }) => {
    test.setTimeout(180_000);
    await runScrobbleSentAfterThreshold(window, isRealScrobble);
  });

  test('scrobble NOT sent when skipping before threshold', async ({ navidromeApp: { window } }) => {
    await runScrobbleNotSentBeforeThreshold(window, isRealScrobble);
  });

  test('seek backward past threshold does not cause double scrobble', async ({
    navidromeApp: { window },
  }) => {
    test.setTimeout(180_000);
    await runSeekBackwardNoDoubleScrobble(window, isRealScrobble);
  });
});

test.describe('Scrobbling — Navidrome + MPV', () => {
  test('scrobble sent after playing past threshold', async ({ navidromeAppMpv: { window } }) => {
    test.setTimeout(180_000);
    await runScrobbleSentAfterThreshold(window, isRealScrobble);
  });

  test('scrobble NOT sent when skipping before threshold', async ({
    navidromeAppMpv: { window },
  }) => {
    await runScrobbleNotSentBeforeThreshold(window, isRealScrobble);
  });

  test('seek backward past threshold does not cause double scrobble', async ({
    navidromeAppMpv: { window },
  }) => {
    test.setTimeout(180_000);
    await runSeekBackwardNoDoubleScrobble(window, isRealScrobble);
  });
});

test.describe('Scrobbling — Jellyfin + Web Audio', () => {
  test('scrobble sent after playing past threshold', async ({ jellyfinApp: { window } }) => {
    test.setTimeout(180_000);
    await runScrobbleSentAfterThreshold(window, isJellyfinPlaybackStopped);
  });

  test('scrobble NOT sent when skipping before threshold', async ({ jellyfinApp: { window } }) => {
    await runScrobbleNotSentBeforeThreshold(window, isJellyfinPlaybackStopped);
  });

  test('seek backward past threshold does not cause double scrobble', async ({
    jellyfinApp: { window },
  }) => {
    test.setTimeout(180_000);
    await runSeekBackwardNoDoubleScrobble(window, isJellyfinPlaybackStopped);
  });
});

test.describe('Scrobbling — Jellyfin + MPV', () => {
  test('scrobble sent after playing past threshold', async ({ jellyfinAppMpv: { window } }) => {
    test.setTimeout(180_000);
    await runScrobbleSentAfterThreshold(window, isJellyfinPlaybackStopped);
  });

  test('scrobble NOT sent when skipping before threshold', async ({
    jellyfinAppMpv: { window },
  }) => {
    await runScrobbleNotSentBeforeThreshold(window, isJellyfinPlaybackStopped);
  });

  test('seek backward past threshold does not cause double scrobble', async ({
    jellyfinAppMpv: { window },
  }) => {
    test.setTimeout(180_000);
    await runSeekBackwardNoDoubleScrobble(window, isJellyfinPlaybackStopped);
  });
});

// ── Edge cases — Navidrome only ────────────────────────────────────────────
// The loop-detection logic (PlayerBar.tsx mpvRestartCount / Player.tsx ended-event
// guard) is server-type-agnostic — the per-backend difference is only which HTTP
// endpoint is called, not whether to call it. Jellyfin edge-case coverage deferred;
// add Jellyfin describe blocks here if a Jellyfin-specific regression is ever observed.

async function runRepeatAllScrobblesEachLoop(window: Page) {
  let scrobbleCount = 0;
  await window.route('**/*', async (route) => {
    if (isRealScrobble(route.request().url())) scrobbleCount++;
    await route.continue();
  });

  await window.click('[data-testid="nav-albums"]');
  await expect(window.locator(`text=${TRACKS.soloTrack.album}`).first()).toBeVisible({
    timeout: 15_000,
  });
  // Albums require a double-click to navigate in — a single click only selects
  // the row (see AlbumList.tsx's useListClickHandler: doubleClick navigates,
  // there is no singleClick override).
  await window.locator(`text=${TRACKS.soloTrack.album}`).first().dblclick();
  await window.locator(`text=${TRACKS.soloTrack.title}`).first().dblclick();
  await window.waitForSelector('[data-testid="player-bar"]');

  const repeatBtn = window.locator('[data-testid="player-repeat"]');
  for (let i = 0; i < 4; i++) {
    if ((await repeatBtn.getAttribute('data-repeat-mode')) === 'all') break;
    await repeatBtn.click();
    await window.waitForTimeout(200);
  }

  await window.waitForTimeout((TRACKS.soloTrack.durationSeconds + 5) * 1000);
  expect(scrobbleCount).toBeGreaterThanOrEqual(1);
  await window.waitForTimeout((TRACKS.soloTrack.durationSeconds + 5) * 1000);
  expect(scrobbleCount).toBeGreaterThanOrEqual(2);
}

async function runRepeatOneScrobblesEachLoop(window: Page) {
  let scrobbleCount = 0;
  await window.route('**/*', async (route) => {
    if (isRealScrobble(route.request().url())) scrobbleCount++;
    await route.continue();
  });

  await window.click('[data-testid="nav-albums"]');
  await expect(window.locator(`text=${TRACKS.soloTrack.album}`).first()).toBeVisible({
    timeout: 15_000,
  });
  // Albums require a double-click to navigate in — a single click only selects
  // the row (see AlbumList.tsx's useListClickHandler: doubleClick navigates,
  // there is no singleClick override).
  await window.locator(`text=${TRACKS.soloTrack.album}`).first().dblclick();
  await window.locator(`text=${TRACKS.soloTrack.title}`).first().dblclick();
  await window.waitForSelector('[data-testid="player-bar"]');

  const repeatBtn = window.locator('[data-testid="player-repeat"]');
  for (let i = 0; i < 4; i++) {
    if ((await repeatBtn.getAttribute('data-repeat-mode')) === 'one') break;
    await repeatBtn.click();
    await window.waitForTimeout(200);
  }

  await window.waitForTimeout((TRACKS.soloTrack.durationSeconds + 5) * 1000);
  expect(scrobbleCount).toBeGreaterThanOrEqual(1);
  await window.waitForTimeout((TRACKS.soloTrack.durationSeconds + 5) * 1000);
  expect(scrobbleCount).toBeGreaterThanOrEqual(2);
}

test.describe('Scrobble edge cases — Web Audio', () => {
  test('repeat:all single-song queue scrobbles each loop', async ({ navidromeApp: { window } }) => {
    test.setTimeout(300_000);
    await runRepeatAllScrobblesEachLoop(window);
  });

  test('repeat:one single-song queue scrobbles each loop', async ({ navidromeApp: { window } }) => {
    test.setTimeout(300_000);
    await runRepeatOneScrobblesEachLoop(window);
  });
});

test.describe('Scrobble edge cases — MPV', () => {
  test('repeat:all single-song queue scrobbles each loop', async ({
    navidromeAppMpv: { window },
  }) => {
    test.setTimeout(300_000);
    await runRepeatAllScrobblesEachLoop(window);
  });

  test('repeat:one single-song queue scrobbles each loop', async ({
    navidromeAppMpv: { window },
  }) => {
    test.setTimeout(300_000);
    await runRepeatOneScrobblesEachLoop(window);
  });
});
