import type { Settings } from '../components/shared/setDefaultSettings';

// os is a Node built-in unavailable in the renderer bundle; derive tmpdir from
// env vars so this module stays importable in both Jest and the renderer.
const tmpDir = process.env.TMPDIR || process.env.TEMP || '/tmp';

export const mockSettings: Partial<Settings> = {
  serverType: 'subsonic',
  language: 'en',
  theme: 'defaultDark',
  showDebugWindow: false,
  globalMediaHotkeys: true,
  systemMediaTransportControls: false,
  cachePath: tmpDir,
  legacyAuth: false,
  artistPageLegacy: false,
  volume: 0.93,
  audioDeviceId: null,
  seekForwardInterval: 5,
  seekBackwardInterval: 5,
  volumeFade: true,
  preservePlayNextOrder: true,
  directPreviousTrack: false,
  hotkeyNavigateBack: 'backspace',
  hotkeySearch: 'ctrl+f',
  hotkeySelectAll: 'ctrl+a',
  hotkeyRemoveSelected: 'del',
  hotkeyPlayPause: 'ctrl+p',
  hotkeyNextTrack: 'ctrl+right',
  hotkeyPrevTrack: 'ctrl+left',
  hotkeyVolumeUp: 'ctrl+up',
  hotkeyVolumeDown: 'ctrl+down',
  hotkeyMute: 'ctrl+m',
  scrobbleThreshold: 90,
  repeat: 'all',
  shuffle: false,
  scrollWithCurrentSong: true,
  cacheImages: true,
  cacheSongs: false,
  pollingInterval: 20,
  fadeDuration: 9,
  fadeType: 'equalPower',
  systemNotifications: false,
  globalShortcuts: false,
  scrobble: false,
  transcode: false,
  sidebar: {
    expand: false,
    width: '165px',
    coverArt: false,
    selected: [],
  },
  pagination: {
    music: {
      recordsPerPage: 50,
      serverSide: true,
    },
    album: {
      recordsPerPage: 50,
      serverSide: false,
    },
  },
  playbackFilters: [
    {
      filter: '(（|\\(|\\[|~|-)[Ii]nst(rumental)?(\\)|\\]|~|-|）)',
      enabled: true,
    },
  ],
  musicFolder: {
    id: null,
    name: null,
    albums: true,
    artists: true,
    dashboard: false,
    search: false,
    starred: false,
    music: true,
  },
  gridCardSize: 200,
  gridGapSize: 20,
  gridAlignment: 'flex-start',
  playlistViewType: 'grid',
  albumViewType: 'grid',
  albumSortDefault: 'random',
  musicSortDefault: 'random',
  musicListFontSize: 13,
  musicListRowHeight: 50,
  musicListColumns: [
    {
      id: '#',
      dataKey: 'index',
      alignment: 'center',
      resizable: true,
      width: 50,
      label: '# (Drag/Drop)',
    },
    {
      id: 'Title',
      dataKey: 'combinedtitle',
      alignment: 'left',
      resizable: true,
      width: 273,
      label: 'Title (Combined)',
    },
    {
      id: 'Album',
      dataKey: 'album',
      alignment: 'left',
      resizable: true,
      width: 263,
      label: 'Album',
    },
    {
      id: 'Duration',
      dataKey: 'duration',
      alignment: 'center',
      resizable: true,
      width: 110,
      label: 'Duration',
    },
    {
      id: 'Bitrate',
      dataKey: 'bitRate',
      alignment: 'left',
      resizable: true,
      width: 72,
      label: 'Bitrate',
    },
    {
      id: 'Fav',
      dataKey: 'starred',
      alignment: 'center',
      resizable: true,
      width: 100,
      label: 'Favorite',
    },
  ],
  albumListFontSize: 14,
  albumListRowHeight: 60,
  albumListColumns: [
    {
      id: '#',
      dataKey: 'index',
      alignment: 'center',
      resizable: true,
      width: 50,
      label: '#',
    },
    {
      id: 'Title',
      dataKey: 'combinedtitle',
      alignment: 'left',
      resizable: true,
      width: 457,
      label: 'Title (Combined)',
    },
    {
      id: 'Tracks',
      dataKey: 'songCount',
      alignment: 'center',
      resizable: true,
      width: 100,
      label: 'Track Count',
    },
    {
      id: 'Duration',
      dataKey: 'duration',
      alignment: 'center',
      resizable: true,
      width: 80,
      label: 'Duration',
    },
    {
      id: 'Fav',
      dataKey: 'starred',
      alignment: 'center',
      resizable: true,
      width: 100,
      label: 'Favorite',
    },
  ],
  artistListFontSize: 14,
  artistListRowHeight: 60,
  artistListColumns: [
    {
      id: '#',
      dataKey: 'index',
      alignment: 'center',
      resizable: true,
      width: 50,
      label: '#',
      rowIndex: 0,
    },
    {
      id: 'Art',
      dataKey: 'coverart',
      alignment: 'center',
      resizable: true,
      width: 74,
      label: 'CoverArt',
      rowIndex: 1,
    },
    {
      id: 'Name',
      dataKey: 'name',
      alignment: 'left',
      flexGrow: 5,
      label: 'Name',
      rowIndex: 2,
    },
    {
      id: 'Album Count',
      dataKey: 'albumCount',
      alignment: 'left',
      flexGrow: 1,
      label: 'Album Count',
      rowIndex: 3,
    },
    {
      id: 'Fav',
      dataKey: 'starred',
      alignment: 'center',
      flexGrow: 1,
      label: 'Favorite',
      rowIndex: 4,
    },
  ],
  genreListFontSize: 14,
  genreListRowHeight: 50,
  genreListColumns: [
    {
      id: '#',
      dataKey: 'index',
      alignment: 'center',
      resizable: true,
      width: 66,
      label: '#',
      rowIndex: 0,
    },
    {
      id: 'Name',
      dataKey: 'name',
      alignment: 'left',
      flexGrow: 5,
      label: 'Name',
      rowIndex: 1,
    },
    {
      id: 'Album Count',
      dataKey: 'albumCount',
      alignment: 'left',
      flexGrow: 1,
      label: 'Album Count',
      rowIndex: 2,
    },
    {
      id: 'Tracks',
      dataKey: 'songCount',
      alignment: 'center',
      flexGrow: 1,
      label: 'Track Count',
      rowIndex: 3,
    },
  ],
  playlistListFontSize: 14,
  playlistListRowHeight: 80,
  playlistListColumns: [
    {
      id: '#',
      dataKey: 'index',
      alignment: 'center',
      resizable: true,
      width: 50,
      label: '#',
    },
    {
      id: 'Art',
      dataKey: 'coverart',
      alignment: 'center',
      resizable: true,
      width: 100,
      label: 'CoverArt',
    },
    {
      id: 'Title',
      dataKey: 'name',
      alignment: 'left',
      resizable: true,
      width: 300,
      label: 'Title',
    },
    {
      id: 'Description',
      dataKey: 'comment',
      alignment: 'left',
      resizable: true,
      width: 200,
      label: 'Description',
    },
    {
      id: 'Tracks',
      dataKey: 'songCount',
      alignment: 'center',
      resizable: true,
      width: 100,
      label: 'Track Count',
    },
    {
      id: 'Owner',
      dataKey: 'owner',
      alignment: 'left',
      resizable: true,
      width: 150,
      label: 'Owner',
    },
    {
      id: 'Modified',
      dataKey: 'changed',
      alignment: 'left',
      resizable: true,
      width: 100,
      label: 'Modified',
    },
  ],
  miniListFontSize: 14,
  miniListRowHeight: 40,
  miniListColumns: [
    {
      id: '#',
      dataKey: 'index',
      alignment: 'center',
      resizable: true,
      width: 50,
      label: '# (Drag/Drop)',
    },
    {
      id: 'Title',
      dataKey: 'title',
      alignment: 'left',
      resizable: true,
      width: 250,
      label: 'Title',
    },
    {
      id: 'Duration',
      dataKey: 'duration',
      alignment: 'center',
      resizable: true,
      width: 80,
      label: 'Duration',
    },
  ],
  font: 'Poppins',
  server: 'http://192.168.14.11:4040',
  serverBase64: 'aHR0cDovLzE5Mi4xNjguMTQuMTE6NDA0MA==',
  dynamicBackground: false,
  retainWindowSize: false,
  savedWindowSize: [1024, 728],
  savedWindowPos: [50, 50],
  defaultWindowWidth: 1024,
  defaultWindowHeight: 728,
  minimizeToTray: true,
  exitToTray: true,
  highlightOnRowHover: false,
  titleBarStyle: 'windows',
  startPage: '/',
  discord: {
    enabled: true,
    clientId: '923372440934055968',
    showAlbumArt: false,
  },
  obs: {
    enabled: true,
    url: '',
    type: 'local',
    path: tmpDir,
    pollingInterval: 2000,
  },
  themesDefault: [],
  themes: [],
};
