import type { Page } from '@playwright/test';
import { test, expect } from '../../fixtures';
import { TRACKS } from '../../fixtures/constants';

// Playwright determines which fixtures a test needs by statically parsing the
// literal destructuring pattern in each test() callback — it cannot resolve a
// computed property name (e.g. `{ [fixture]: { window } }`) at runtime, so the
// two backends below are intentionally written out as literal test.describe
// blocks rather than generated by looping over an array. Shared logic lives in
// these helper functions so the test bodies aren't duplicated.

async function checkTrackTitleAndAlbumArt(window: Page) {
  await window.click('[data-testid="nav-albums"]');
  await expect(window.locator(`text=${TRACKS.track01.album}`).first()).toBeVisible({
    timeout: 15_000,
  });
  // Albums require a double-click to navigate in — a single click only selects
  // the row (see AlbumList.tsx's useListClickHandler: doubleClick navigates,
  // there is no singleClick override).
  await window.locator(`text=${TRACKS.track01.album}`).first().dblclick();
  await window.locator(`text=${TRACKS.track01.title}`).first().dblclick();
  await window.waitForSelector('[data-testid="player-bar"]');

  await expect(window.locator('[data-testid="player-track-title"]')).toContainText(
    TRACKS.track01.title,
    { timeout: 10_000 }
  );

  const art = window.locator('[data-testid="player-album-art"]');
  await expect(art).toBeVisible();
  const src = await art.getAttribute('src');
  expect((src ?? '').length).toBeGreaterThan(10);
}

async function checkTimeCounterAdvances(window: Page) {
  await window.click('[data-testid="nav-albums"]');
  await expect(window.locator(`text=${TRACKS.track01.album}`).first()).toBeVisible({
    timeout: 15_000,
  });
  // Albums require a double-click to navigate in — a single click only selects
  // the row (see AlbumList.tsx's useListClickHandler: doubleClick navigates,
  // there is no singleClick override).
  await window.locator(`text=${TRACKS.track01.album}`).first().dblclick();
  await window.locator(`text=${TRACKS.track01.title}`).first().dblclick();
  await window.waitForSelector('[data-testid="player-bar"]');

  // Wait for counter to become non-zero first
  await window.waitForFunction(
    () => {
      const el = document.querySelector('[data-testid="player-current-time"]');
      return el?.textContent !== '0:00';
    },
    { timeout: 15_000 }
  );

  const t1 = await window.locator('[data-testid="player-current-time"]').textContent();
  await window.waitForTimeout(3000);
  const t2 = await window.locator('[data-testid="player-current-time"]').textContent();
  expect(t1).not.toEqual(t2);
}

async function checkPauseResume(window: Page) {
  await window.click('[data-testid="nav-albums"]');
  await expect(window.locator(`text=${TRACKS.track01.album}`).first()).toBeVisible({
    timeout: 15_000,
  });
  // Albums require a double-click to navigate in — a single click only selects
  // the row (see AlbumList.tsx's useListClickHandler: doubleClick navigates,
  // there is no singleClick override).
  await window.locator(`text=${TRACKS.track01.album}`).first().dblclick();
  await window.locator(`text=${TRACKS.track01.title}`).first().dblclick();
  await window.waitForFunction(
    () => document.querySelector('[data-testid="player-current-time"]')?.textContent !== '0:00',
    { timeout: 15_000 }
  );

  await window.click('[data-testid="player-play-pause"]');
  await window.waitForTimeout(500);
  const t1 = await window.locator('[data-testid="player-current-time"]').textContent();
  await window.waitForTimeout(2000);
  const t2 = await window.locator('[data-testid="player-current-time"]').textContent();
  expect(t1).toEqual(t2); // paused — should not advance

  await window.click('[data-testid="player-play-pause"]');
  await window.waitForTimeout(3000);
  const t3 = await window.locator('[data-testid="player-current-time"]').textContent();
  expect(t2).not.toEqual(t3); // resumed — should advance
}

async function checkSkipToNext(window: Page) {
  await window.click('[data-testid="nav-albums"]');
  await expect(window.locator(`text=${TRACKS.track01.album}`).first()).toBeVisible({
    timeout: 15_000,
  });
  // Albums require a double-click to navigate in — a single click only selects
  // the row (see AlbumList.tsx's useListClickHandler: doubleClick navigates,
  // there is no singleClick override).
  await window.locator(`text=${TRACKS.track01.album}`).first().dblclick();
  await window.locator(`text=${TRACKS.track01.title}`).first().dblclick();
  await window.waitForSelector('[data-testid="player-bar"]');
  await window.waitForTimeout(2000);

  await window.click('[data-testid="player-next"]');
  await expect(window.locator('[data-testid="player-track-title"]')).toContainText(
    TRACKS.track02.title,
    { timeout: 10_000 }
  );
}

async function checkRepeatNoneStopsAtEnd(window: Page) {
  await window.click('[data-testid="nav-albums"]');
  await expect(window.locator(`text=${TRACKS.track01.album}`).first()).toBeVisible({
    timeout: 15_000,
  });
  // Albums require a double-click to navigate in — a single click only selects
  // the row (see AlbumList.tsx's useListClickHandler: doubleClick navigates,
  // there is no singleClick override).
  await window.locator(`text=${TRACKS.track01.album}`).first().dblclick();
  await window.locator(`text=${TRACKS.track03.title}`).first().dblclick();
  await window.waitForSelector('[data-testid="player-bar"]');

  // Ensure repeat:none
  const repeatBtn = window.locator('[data-testid="player-repeat"]');
  for (let i = 0; i < 4; i++) {
    if ((await repeatBtn.getAttribute('data-repeat-mode')) === 'none') break;
    await repeatBtn.click();
    await window.waitForTimeout(200);
  }

  await window.waitForTimeout((TRACKS.track03.durationSeconds + 10) * 1000);
  const isPlaying = await window
    .locator('[data-testid="player-play-pause"]')
    .getAttribute('data-playing');
  expect(isPlaying).not.toBe('true');
}

async function checkRepeatAllWrapsToFirst(window: Page) {
  await window.click('[data-testid="nav-albums"]');
  await expect(window.locator(`text=${TRACKS.track01.album}`).first()).toBeVisible({
    timeout: 15_000,
  });
  // Albums require a double-click to navigate in — a single click only selects
  // the row (see AlbumList.tsx's useListClickHandler: doubleClick navigates,
  // there is no singleClick override).
  await window.locator(`text=${TRACKS.track01.album}`).first().dblclick();
  await window.locator(`text=${TRACKS.track03.title}`).first().dblclick();
  await window.waitForSelector('[data-testid="player-bar"]');

  const repeatBtn = window.locator('[data-testid="player-repeat"]');
  for (let i = 0; i < 4; i++) {
    if ((await repeatBtn.getAttribute('data-repeat-mode')) === 'all') break;
    await repeatBtn.click();
    await window.waitForTimeout(200);
  }

  await window.waitForTimeout((TRACKS.track03.durationSeconds + 10) * 1000);
  await expect(window.locator('[data-testid="player-track-title"]')).toContainText(
    TRACKS.track01.title,
    { timeout: 10_000 }
  );
}

test.describe('Playback — web backend', () => {
  test('track title and album art shown in player bar', async ({ navidromeApp: { window } }) => {
    await checkTrackTitleAndAlbumArt(window);
  });

  test('time counter advances during playback', async ({ navidromeApp: { window } }) => {
    await checkTimeCounterAdvances(window);
  });

  test('pause stops time counter, resume continues it', async ({ navidromeApp: { window } }) => {
    await checkPauseResume(window);
  });

  test('skip to next track', async ({ navidromeApp: { window } }) => {
    await checkSkipToNext(window);
  });

  test.describe('Repeat modes — web backend', () => {
    test('repeat:none stops at end of queue', async ({ navidromeApp: { window } }) => {
      test.setTimeout(120_000);
      await checkRepeatNoneStopsAtEnd(window);
    });

    test('repeat:all wraps to first track', async ({ navidromeApp: { window } }) => {
      test.setTimeout(120_000);
      await checkRepeatAllWrapsToFirst(window);
    });
  });
});

test.describe('Playback — mpv backend', () => {
  test('track title and album art shown in player bar', async ({ navidromeAppMpv: { window } }) => {
    await checkTrackTitleAndAlbumArt(window);
  });

  test('time counter advances during playback', async ({ navidromeAppMpv: { window } }) => {
    await checkTimeCounterAdvances(window);
  });

  test('pause stops time counter, resume continues it', async ({ navidromeAppMpv: { window } }) => {
    await checkPauseResume(window);
  });

  test('skip to next track', async ({ navidromeAppMpv: { window } }) => {
    await checkSkipToNext(window);
  });

  test.describe('Repeat modes — mpv backend', () => {
    test('repeat:none stops at end of queue', async ({ navidromeAppMpv: { window } }) => {
      test.setTimeout(120_000);
      await checkRepeatNoneStopsAtEnd(window);
    });

    test('repeat:all wraps to first track', async ({ navidromeAppMpv: { window } }) => {
      test.setTimeout(120_000);
      await checkRepeatAllWrapsToFirst(window);
    });
  });
});
